# This is a basic workflow to help you get started with Actions.
name: register-services

# Variables
env:
  KEY1: 'value1'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
on: 
  workflow_dispatch:
    inputs:
      nowServer:
        description: 'NOW Server'     
        required: true
        default: 'https://aiopsstage02.service-now.com'
      serviceMap:
        description: 'Service Map'
        required: true
        default: 'discovery'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Git Repo
      uses: actions/checkout@v2
      
    # Register Services
    - name: Register Services
      env: 
        NOW_API: ${{ github.event.inputs.nowServer }}/api/sn_sro/service_registration/builder
      run : |
        echo $NOW_API
        curl -X POST -H "Content-Type: application/json" $NOW_API \
        --user ${{ secrets.NOW_USERNAME }}:${{ secrets.NOW_PASSWORD }} \
        -d @registration/${{ github.event.inputs.serviceMap }}.json